services:
  - type: web
    name: ai-pr-reviewer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 api_server.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
